symbols:
- DCM
- DPM
- PET
- LAS
- REE
- BFC
- PVS
- GMD
- NVL
- PVD
- ACC
- GAS
- IDC
- GVR
- VSC
- ADG
- CSV
- DGW
- STB
- PAN
- DPR
- FMC
- PNJ
- VHC
- MBB
- VCG
- FRT
- SIP
- KOS
- PHR
- LPB
- EIB
- ABS
- HPG
- VNM
- BID
- VPI
- HCM
- CTR
- VCB
- HHV
- ADP
- HAH
- ACB
- TPB
- ADS
- SSI
- NLG
- OCB
- VPB
- MSN
- CTG
- SSB
- AGG
- TCB
- MWG
- HSG
- HDB
- BCC
- SAB
- DGC
- FCN
- NKG
- AAA
- AGR
- APG
- SZC
- AAM
- ANT
- VIX
- CII
- ACG
- APH
- CMG
- VHM
- NTP
- VND
- DXG
- SHS
- ABT
- BCM
- ANV
- ASM
- KBC
- ABR
- MPC
- PDR
- ACL
- FPT
- DIG
- AFX
- BMP
- VIC
- AAT
- CEO
- KDH
- VRE
