symbols:
  - ACB
  - ABS
  - ACC
  - ANV
  - AGG
  - AAA
  - AGR
  - APH
  - ADG
  - ADS
  - ANT
  - ADP
  - APG
  - ACL
  - ACG
  - ABT
  - AFX
  - AAM
  - ABR
  - AAT
  - FPT
  - MWG
  - HPG
  - VCB
  - MBB
  - TCB
  - CTG
  - BID
  - SSI
  - VND
  - HCM
  - VIX
  - SHS
  - DIG
  - DXG
  - NLG
  - KDH
  - PDR
  - VIC
  - VHM
  - BCM
  - GVR
  - DGC
  - DPM
  - DCM
  - GAS
  - PVS
  - PVD
  - REE
  - IDC
  - VNM
  - MSN
  - SAB
  - PNJ
  - STB
  - TPB
  - VPB
  - EIB
  - OCB
  - HDB
  - LPB
  - SSB
  - VRE
  - NVL
  - KBC
  - HAH
  - GMD
  - VSC
  - HSG
  - NKG
  - PHR
  - DPR
  - CTR
  - CMG
  - DGW
  - PET
  - FRT
  - PC1
  - FCN
  - CII
  - HHV
  - VCG
  - KOS
  - CEO
  - VPI
  - SZC
  - SIP
  - BMP
  - NTP
  - HT1
  - BCC
  - LAS
  - BFC
  - CSV
  - LTG
  - PAN
  - FMC
  - VHC
  - MPC
  - ASM
