symbols:
- DCM
- DPM
- REE
- PVS
- ACC
- ADG
- GAS
- PVD
- IDC
- GVR
- MBB
- HPG
- ABS
- BID
- VCB
- ADP
- ACB
- SSI
- NLG
- ADS
- HCM
- CTG
- AGG
- TCB
- MWG
- AAM
- DGC
- ACG
- AGR
- APG
- AAA
- ANT
- VIX
- APH
- DXG
- ACL
- VHM
- BCM
- ABT
- VND
- ANV
- SHS
- PDR
- ABR
- FPT
- DIG
- AFX
- AAT
- KDH
- VIC
